#NumPy

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
import numpy as np

# Creating a NumPy array
a = np.array([1, 2, 3])

# Performing mathematical operations
print("Array:", a)
print("Mean of the array:", np.mean(a))

Array: [1 2 3]
Mean of the array: 2.0


In [ ]:
import numpy as np

# Create a 2-D array by passing a list of lists into array().
A = np.array([[1, 2, 3], [4, 5, 6]])
print("Array A: \n",A)

# Create a 2-D matrix by passing a list of lists into matrix().
M = np.matrix([[1, 2, 3], [4, 5, 6]])
print("Matrix M: \n",M)

Array A: 
 [[1 2 3]
 [4 5 6]]
Matrix M: 
 [[1 2 3]
 [4 5 6]]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]], dtype='float')
print("Array A: \n",A)
# 'A' is a 2-D array with 2 rows, 3 columns, and 6 entries.
print(A.ndim, A.shape, A.size)

Array A: 
 [[1. 2. 3.]
 [4. 5. 6.]]
2 (2, 3) 6


In [ ]:
# Creating a NumPy array with specified values
array1 = ....

# Creating a 2x3 NumPy array filled with zeros
array2 = ....

# Creating a 2x3 NumPy array filled with ones
array3 = ...

In [ ]:
array1

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
print("array1: \n",array1)
print("array2: \n",array2)
print("array3: \n",array3)

array1: 
 [[0 1 2]
 [2 3 4]]
array2: 
 [[0. 0. 0.]
 [0. 0. 0.]]
array3: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Creating a 3x3 NumPy array
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extracting the diagonal entries of 'A' as a 1-D array
diagonal = ...

# The expected output would be the diagonal elements of the array
print(diagonal)

[1 5 9]


In [ ]:
# Creating an identity matrix of size 3x3
array1 = ...

# Creating an array with a range of values from 0 to 10 with a step of 2
array2 = np.arange(0, 10, 2)

# Creating a 3x3 array of random integers between 0 and 10
array3 = np.random.randint(0, 10, (3, 3))

In [ ]:
print("array1: \n",array1)
print("array2: \n",array2)
print("array3: \n",array3)

array1: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
array2: 
 [0 2 4 6 8]
array3: 
 [[0 0 7]
 [1 9 4]
 [3 7 0]]


In [ ]:
dir(array1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [ ]:
# diag() can also be used to create a diagonal matrix from a 1-D array.
np.diag([1, 11, 111])

array([[  1,   0,   0],
       [  0,  11,   0],
       [  0,   0, 111]])

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
print(arr*arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [ ]:
print(arr-arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(arr**2)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
# Perform an element-wise comparison to check if elements in 'arr2' are greater than those in 'arr'
print(arr2 > arr)

[[False  True False]
 [ True False  True]]


In [ ]:
# Make an array of the integers from 0 to 10 (exclusive).
x = np.arange(10)
# The element at index 3.
single_element = x[3]
single_element

3

In [ ]:
x[5]

5

In [ ]:
# Everything before index 3.
first_slice = x[:5]
first_slice

array([0, 1, 2, 3, 4])

In [ ]:
# Everything from index 3 on.
second_slice = x[3:]
second_slice

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Everything between index 3 and index 8 (exclusive).
third_slice = x[3:8]
third_slice

array([3, 4, 5, 6, 7])

In [ ]:
#Use a comman to separate the dimensions for multi-dimensional arrays.
A = ...
#The element at row 1, column 2.
.

7

In [ ]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#All of the rows, from column 2 on.
.

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [ ]:
#All of the rows, till 2.
A[:, :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
# Create an array of integers from 0 to 40 by tens
x = np.arange(0, 50, 10)
# Integer array indexing
index = np.array([3, 1, 4])
selected_elements = x[index]
selected_elements

array([30, 10, 40])

In [ ]:
x

array([ 0, 10, 20, 30, 40])

In [ ]:
# Boolean array indexing
mask = np.array([True, False, False, True, False])
selected_elements_masked = x[mask]
selected_elements_masked

array([ 0, 30])

In [ ]:
# Create an array with every other integer from 10 to 18.
y = np.arange(10, 20, 2)

# Create a boolean mask to identify elements greater than 15.
mask = y > 15

# Use the mask to select elements from 'y'.
selected_elements = ...
selected_elements

array([16, 18])

In [ ]:
y

array([10, 12, 14, 16, 18])

In [ ]:
# Change elements of 'y' where the mask is True to 100.
y[mask] = 100

# Print the updated array.
print(y)

[ 10  12  14 100 100]


In [ ]:
A = np.arange(12)
print(A)
# Reshape 'A' into a 3x4 two-dimensional array.
reshaped_3x4 = A.reshape((3, 4))
reshaped_3x4

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Reshape 'A' into a two-dimensional array with 2 rows and the appropriate number of columns.
# The -1 means that the exact number of columns will be automatically calculated.
reshaped_2x_ = A.reshape((-1, 2))
reshaped_2x_

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
A = np.arange(12).reshape((4,3))
x = np.arange(3)

# Add the 1D array 'x' to each row of the 2D array 'A'
result = A + x

# Print the result
result

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [ ]:
x = np.arange(-2, 3)

# Print the array of absolute values
print(np.abs(x))

# Calculate and print the sine of each element in the array x
sin_x = np.sin(x)
print(sin_x)

[2 1 0 1 2]
[-0.90929743 -0.84147098  0.          0.84147098  0.90929743]


In [ ]:
a = np.array([[0., 1., 2.], [3., 4., 5.]])
print("Original: \n",a)
# Transposing the array 'a' using the .transpose() method
a_transposed = a.transpose()
print("Transposed: \n",a_transposed)

Original: 
 [[0. 1. 2.]
 [3. 4. 5.]]
Transposed: 
 [[0. 3.]
 [1. 4.]
 [2. 5.]]


In [ ]:
# Flatten the array 'a' and print the result
flattened_a = a.flatten()
print(flattened_a)

[0. 1. 2. 3. 4. 5.]


In [ ]:
# Create two 2x2 arrays with float type elements
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)

# Concatenate 'a' and 'b' along axis 0 (vertically)
concatenated_axis0 = ..
print("concatenated_axis0: \n", concatenated_axis0)

# Concatenate 'a' and 'b' along axis 1 (horizontally)
concatenated_axis1 = ...
print("concatenated_axis1: \n", concatenated_axis1)

concatenated_axis0: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
concatenated_axis1: 
 [[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


#Pandas

In [ ]:
import pandas as pd
print(pd.__version__)

1.5.3


In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
data['b']

0.5

In [ ]:
population_dict = {'California': 38332521, 'Texas': 26448193, 'New York': 19651127,
                   'Florida': 19552860, 'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [ ]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

In [ ]:
import numpy as np
import pandas as pd
df2 = pd.DataFrame(np.random.randint(low=0, high=10, size=(5, 5)),
                   columns=['a', 'b', 'c', 'd', 'e'])
df2

a  b  c  d  e
0  9  5  1  0  1
1  1  0  6  9  9
2  1  6  2  7  6
3  8  4  3  2  2
4  8  3  9  9  6

In [ ]:
area_dict = {'California': 423967, 'New York': 141297, 'Illinois': 149995}
area = pd.Series(area_dict)

In [ ]:
states = pd.DataFrame({'population': population, 'area': area})
states

population      area
California    38332521  423967.0
Florida       19552860       NaN
Illinois      12882135  149995.0
New York      19651127  141297.0
Texas         26448193       NaN

In [ ]:
import pandas as pd

list2 = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
df = pd.DataFrame(list2)
print(df)
df.columns = ['V1', 'V2', 'V3']
print(df)

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8
   V1  V2  V3
0   0   1   2
1   3   4   5
2   6   7   8


In [ ]:
import pandas as pd

df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
}, index=['KZ', 'RU', 'BY', 'UA'])

print(df)

       country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628


In [ ]:
# Create the DataFrame
.

# Set the index to country codes and name the index
.

# Print the updated DataFrame
print(df)

                 country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628


In [ ]:
print(df.loc['KZ'])

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object


In [ ]:
print(df.iloc[0])

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object


In [ ]:
print(df.loc[['KZ', 'RU'], 'population'])

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64


In [ ]:
print(df.loc['KZ':'BY', :])

                 country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600


In [ ]:
print(df[df.population > 10][['country', 'square']])

                 country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UA               Ukraine    603628


In [ ]:
df = df.drop('population', axis='columns')
df

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
BY               Belarus    207600
UA               Ukraine    603628

In [ ]:
df.tail()

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
BY               Belarus    207600
UA               Ukraine    603628

In [ ]:
# Read a CSV file into a DataFrame
df = ..
# Write the DataFrame to a CSV file
df...

In [ ]:
import pandas as pd

population_dict = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135,
    'Georgia': 12546378,
    'Oklahoma': 90785645,
    'Iowa': 36764589,
    'Ohio': 34549078
}
population = pd.Series(population_dict)

area_dict = {
    'California': 423967,
    'New York': 141297,
    'Illinois': 149995,
    'Oklahoma': 784536,
    'Texas': 463517
}
area = pd.Series(area_dict)

In [ ]:
states = pd.DataFrame(...)
states

population      area
California    38332521  423967.0
Florida       19552860       NaN
Georgia       12546378       NaN
Illinois      12882135  149995.0
Iowa          36764589       NaN
New York      19651127  141297.0
Ohio          34549078       NaN
Oklahoma      90785645  784536.0
Texas         26448193  463517.0

In [ ]:
states.head()

population      area
California    38332521  423967.0
Florida       19552860       NaN
Georgia       12546378       NaN
Illinois      12882135  149995.0
Iowa          36764589       NaN

In [ ]:
states.tail()

population      area
Iowa        36764589       NaN
New York    19651127  141297.0
Ohio        34549078       NaN
Oklahoma    90785645  784536.0
Texas       26448193  463517.0

In [ ]:
states.index

Index(['KZ', 'RU', 'BY', 'UA'], dtype='object', name='Country Code')

In [ ]:
states.columns

Index(['population', 'area'], dtype='object')

In [ ]:
df1 = pd.DataFrame({
    'Math': [88, 92, 85, 95],'Science': [90, 87, 91, 78],
    'English': [86, 89, 93, 80]
})
# Calculate the mean of each column
column_means = ....
print("Mean of each column:")
print(column_means)

Mean of each column:
Math       90.0
Science    86.5
English    87.0
dtype: float64


In [ ]:
df2 = pd.DataFrame({
    'Exam1': [75, 88, 92],'Exam2': [78, 90, 94],'Exam3': [85, 80, 88]
})
# Calculate the mean of each row (i.e., the average score of each student across all exams)
row_means = df2.mean(axis=1)
print("Average score of each student across all exams:")
print(row_means)

Average score of each student across all exams:
0    79.333333
1    86.000000
2    91.333333
dtype: float64


In [ ]:
df1 = pd.DataFrame({'key': ['foo', 'bar'], 'lval': [1, 2]})
df2 = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4, 5]})

# Perform the merge operation based on the common column 'key'
result = pd.merge(df1, df2, on='key')
print(result)

   key  lval  rval
0  foo     1     4
1  bar     2     5


In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

df2 = pd.DataFrame({
    'A': [7, 8, 9],
    'B': [10, 11, 12]
})

# Append df2 to df1
result = df1.append(df2, ignore_index=True)
print(result)

   A   B
0  1   4
1  2   5
2  3   6
3  7  10
4  8  11
5  9  12


<ipython-input-42-88e4d36b3f64>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = df1.append(df2, ignore_index=True)


In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.DESCR)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(iris.data)
X_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = ...

In [ ]:
X_test

In [ ]:
from sklearn.linear_model import LogisticRegression
model =.
model..

LogisticRegression()

In [ ]:
from sklearn.metrics import accuracy_score
predictions = ..
accuracy = ...
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.96


In [ ]:
y_test

array([0, 2, 0, 1, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1,
       2, 1, 0, 2, 1, 1, 0, 0, 0, 1, 2, 0, 2, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 2, 1, 1, 1, 0, 2, 1, 1, 2, 0, 2, 0, 2, 2, 2, 2,
       1, 1, 1, 1, 2, 0, 2, 2, 0])

In [ ]:
predictions

array([0, 2, 0, 1, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1,
       2, 1, 0, 2, 2, 1, 0, 0, 0, 1, 2, 0, 2, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 2, 1, 1, 1, 0, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 2,
       1, 1, 1, 2, 2, 0, 2, 2, 0])

In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Define the k-fold cross-validator (k=5)
kfold = ..

# Perform k-fold cross-validation
results = ..

# Output the accuracy of each fold
print("Accuracy per fold: ", results)

# Average accuracy
print("Average accuracy: ", results.mean())


Accuracy per fold:  [1.         0.93333333 0.93333333 1.         1.         0.93333333
 1.         0.86666667 1.         0.86666667]
Average accuracy:  0.9533333333333334


In [ ]:
type(X_test)

numpy.ndarray

In [ ]:
X_test.shape

(75, 4)